language: rust
cache: cargo
deploy:
  provider: pages
  local-dir: docs
  keep-history: true
  target-branch: gh-pages
  skip-cleanup: true
  github-token:
    secure: "MZb/rJn+p5786aAh2OOJemzZhI3jnJxkzMvcmEV517/No9KJNLE8SFMC0wceVM3NZ9yb0a9PZTWbJ5dRp3pgSdWAI0/qhAnin2LrWc4Vh76SEN8RxdxJjmr7ixQ58M95PAhJ4do6Iv8Nmi3K3gbwX+mi/OmhY281xFT729I69S35gLyCh0zCrPsGpbqeFnVDgRvwQdjpY3wcWeUFyOQ+ZcvRuUTnnJLTtvmrwMUf2TTeHKDwVrQKAFuUUv0Fu6ouXcldqU8h0ewN3ARdIDUREdMNlMFm6UZvIx1BZ+lvIUx5W8DOkY8m4AgLDCW4GxKw6j0aZWe66QUCRxu1p0mgA+AvtQMvYs40IZHYnB7thkAC/DKCukn1yX/aa1tQo0yUQ88/bUrFUz4hPudy00DyGjaBXM24YH+n3o59PQGQqW249ajk8Sp21jX9C1eP8VHtbP4uI13ol9DHkhPERZrMi2CoJfH8rVo2WNz+YQnrVX+gloO3/PtTJQh8iwET4Voo5TBTSHHGMPzUe5ZU6lsesZp29JEeJEdA6me6eA4mrpp9fwK54BHscEwu1w28e/u2OmwqOvn6izz6xioLDiyEKMDBbYeJn2Bv24v2CkSfW6kcwsTFd+GRODNb4bN59UD3owLAt0afdDz7PW2oarorVXloOgmL88u/QdcQZucd0C0="
  on:
    branch: master
script:
- cargo test --features FePresentation,VK_EXT_debug_report
- ./update_doc.sh
